// Generated by BUCKLESCRIPT VERSION 1.7.5, PLEASE EDIT WITH CARE
'use strict';

var $$Array     = require("bs-platform/lib/js/array.js");
var Block       = require("bs-platform/lib/js/block.js");
var Curry       = require("bs-platform/lib/js/curry.js");
var React       = require("react");
var RepoData    = require("./repoData.js");
var RepoItem    = require("./repoItem.js");
var ReasonReact = require("reason-react/lib/js/src/reasonReact.js");

var component = ReasonReact.statefulComponent("App");

function handleReposLoaded(repos, _, _$1) {
  return /* Update */Block.__(0, [/* record */[/* repos : Some */[repos]]]);
}

function make(_, _$1) {
  var newrecord = component.slice();
  newrecord[/* didMount */4] = (function (_, self) {
      RepoData.fetchRepos(/* () */0).then((function (repos) {
              Curry._2(self[/* update */2], handleReposLoaded, repos);
              return Promise.resolve(/* () */0);
            }));
      return /* NoUpdate */0;
    });
  newrecord[/* render */9] = (function (state, _) {
      var match = state[/* repos */0];
      var repoItem = match ? $$Array.map((function (repo) {
                return ReasonReact.element(/* Some */[repo[/* full_name */0]], /* None */0, RepoItem.make(repo, /* array */[]));
              }), match[0]) : "Loading";
      return React.createElement("div", {
                  className: "App"
                }, React.createElement("div", {
                      className: "App-header"
                    }, React.createElement("h1", undefined, "Reason Projects")), repoItem);
    });
  newrecord[/* initialState */10] = (function () {
      return /* record */[/* repos : None */0];
    });
  return newrecord;
}

exports.component         = component;
exports.handleReposLoaded = handleReposLoaded;
exports.make              = make;
/* component Not a pure module */
