// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';

var Json_decode = require("bs-json/lib/js/src/Json_decode.js");

function parseRepoJson(json) {
  return /* record */[
          /* full_name */Json_decode.field("full_name", Json_decode.string, json),
          /* stargazers_count */Json_decode.field("stargazers_count", Json_decode.$$int, json),
          /* html_url */Json_decode.field("html_url", Json_decode.string, json)
        ];
}

function parseReposResponseJson(json) {
  return Json_decode.field("items", (function (param) {
                return Json_decode.array(parseRepoJson, param);
              }), json);
}

var reposUrl = "https://api.github.com/search/repositories?q=topic%3Areasonml&type=Repositories";

function fetchRepos() {
  return fetch(reposUrl).then((function (prim) {
                  return prim.text();
                })).then((function (jsonText) {
                return Promise.resolve(parseReposResponseJson(JSON.parse(jsonText)));
              }));
}

exports.parseRepoJson          = parseRepoJson;
exports.parseReposResponseJson = parseReposResponseJson;
exports.reposUrl               = reposUrl;
exports.fetchRepos             = fetchRepos;
/* No side effect */
