// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE

import * as Jest from "@glennsl/bs-jest/src/jest.js";

Jest.test("addition", (function () {
        return Jest.Expect[/* toBe */2](7, Jest.Expect[/* expect */0](7));
      }));

export {
  
}
/*  Not a pure module */
