// Generated by BUCKLESCRIPT VERSION 1.7.5, PLEASE EDIT WITH CARE
'use strict';

var React       = require("react");
var Pervasives  = require("bs-platform/lib/js/pervasives.js");
var ReasonReact = require("reason-react/lib/js/src/reasonReact.js");

var component = ReasonReact.statelessComponent("RepoItem");

function make(repo, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function (_, _$1) {
      return React.createElement("div", {
                  className: "RepoItem"
                }, React.createElement("a", {
                      href: repo[/* html_url */2]
                    }, React.createElement("h2", undefined, repo[/* full_name */0])), Pervasives.string_of_int(repo[/* stargazers_count */1]) + " stars");
    });
  return newrecord;
}

exports.component = component;
exports.make      = make;
/* component Not a pure module */
